### ISSUE TITLE
start and end parameters exception

### ISSUE THREAD

**Issue by meow-watermelon** [meow-watermelon/host-monitoring-station#10]
`end=start-8h` would return HTTP response code 500 with following exception:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "hms_web.py", line 49, in hms_load_graphs
    g.cpu_graph_filename = hms_graph.plot_cpu_graph()
  File "/home/ericlee/host-monitoring-station/src/hms/graph.py", line 103, in plot_cpu_graph
    rrdtool.graph(
rrdtool.OperationalError: the start and end times cannot be specified relative to each other
```

**Comment by meow-watermelon** [comment]
commit: https://github.com/meow-watermelon/host-monitoring-station/commit/697000ae106ee86fddebc4dde3978c786b9dd2fe
